### PR TITLE
Add test statistics to mnl

### PR DESCRIPTION
**Pull request by Arezoo-bz**
This PR closes issue #28. 
screen shot 2018-06-29 at 10 47 36

### CODE REVIEW

**Comment by Eh2406** [comment]
Glad to see this added! Should it also get back ported to the original urbansim copy of this code?

**Comment by smmaurer** [comment]
@Arezoo-bz This is fantastic!! So great to have all of this

@Eh2406 It shouldn't take much surgery for the current version of urbansim to display a table like this -- i'll open up an issue in that repo

**Comment by smmaurer** [comment]
@Arezoo-bz We should figure out why the Travis build is failing before merging this, though -- it looks like a real error, but only in Python 3.6 for some reason. I can help diagnose this on Monday.

**Comment by gboeing** [comment]
@smmaurer @Arezoo-bz CI test failure fixed in #34

**Pull request merged**
